export const CREATE_SINGLE_CHAT = "CREATE_SINGLE_CHAT";
export const GET_ALL_CHAT = "GET_ALL_CHAT";
export const CREATE_GROUP_CHAT = "CREATE_GROUP_CHAT";
export const BLOCK_USER = "BLOCK_USER";
export const UNBLOCK_USER = "UNBLOCK_USER";
export const EXIT_GROUP = "EXIT_GROUP";
// export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
