export const CREATE_NEW_MESSAGE = "CREATE_NEW_MESSAGE";
export const GET_ALL_MESSAGE = "GET_ALL_MESSAGE";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const EDIT_MESSAGE = "EDIT_MESSAGE";
